name: 'Setup MySQL'
description: 'Setup MySQL database'
author: 'Christian Weinberger'
branding:
  icon: 'database'
inputs:
  version:
    description: 'The MySQL version'
    required: false
    default: 'latest'
  hostName:
    description: 'The hostname'
    required: false
    default: "mysql"
  hostPort:
    description: 'The port of host'
    required: false
    default: 3306
  containerPort:
    description: 'The port of container'
    required: false
    default: 3306
  rootPassword:
    description: 'The root user password'
    required: false
    default: ''
  user:
    description: 'The MySQL user to create'
    required: false
    default: ''
  password:
    description: 'The password for the MySQL user'
    required: false
    default: ''
  database:
    description: 'Name for the initial database to create'
    required: false
    default: 'TestDatabase'
  characterSet:
    description: 'The character set of MySQL server'
    required: false
    default: 'utf8mb4'
  collation:
    description: 'The collation of MySQL server'
    required: false
    default: 'utf8mb4_general_ci'
  sqlMode:
    description: 'The sql modes, fx. NO_ENGINE_SUBSTITUTION'
    required: false
    default: 'NO_ENGINE_SUBSTITUTION'
  explicitDefaultsForTimestamp:
    description: 'The --explicit-defaults-for-timestamp flag'
    required: false
    default: ''
  characterSetFilesystem:
    description: 'The --character-set-filesystem flag'
    required: false
    default: ''
  innodbAutoIncLockMode:
    description: 'The --innodb_autoinc_lock_mode flag'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
